name: zzu_jksb

on:
  schedule:
    - cron: '0/30 23 * * *'
  push:
    branches: [ action ]
  watch:
    types: [started]
  workflow_dispatch:
  

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.7
      uses: actions/setup-python@v2
      with:
        python-version: 3.7
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install requests
  # if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    
    - name: jksb
      env:
        id: ${{ secrets.id }}
        pwd: ${{ secrets.pwd }}
        key: ${{ secrets.key }}
      run: |
        python jksb.py
